export default {
    CODECS_VIDEO: {
        "012v": "Uncompressed 4:2:2 10-bit",
        "4xm": "4X Movie",
        "8bps": "QuickTime 8BPS video",
        "a64_multi": "Multicolor charset for Commodore 64",
        "a64_multi5": "Multicolor charset for Commodore 64, extended with 5th color (colram)",
        "aasc": "Autodesk RLE",
        "aic": "Apple Intermediate Codec",
        "amv": "AMV Video",
        "anm": "Deluxe Paint Animation",
        "ansi": "ASCII/ANSI art",
        "asv1": "ASUS V1",
        "asv2": "ASUS V2",
        "aura": "Auravision AURA",
        "aura2": "Auravision Aura 2",
        "av1": "Alliance for Open Media AV1",
        "avrn": "Avid AVI Codec",
        "avrp": "Avid 1:1 10-bit RGB Packer",
        "avs": "AVS (Audio Video Standard) video",
        "avs2": "AVS2-P2/IEEE1857.4",
        "avui": "Avid Meridien Uncompressed",
        "ayuv": "Uncompressed packed MS 4:4:4:4",
        "bethsoftvid": "Bethesda VID video",
        "bfi": "Brute Force & Ignorance",
        "binkvideo": "Bink video",
        "bintext": "Binary text",
        "bitpacked": "Bitpacked",
        "bmp": "BMP (Windows and OS/2 bitmap)",
        "bmv_video": "Discworld II BMV video",
        "c93": "Interplay C93",
        "cavs": "Chinese AVS (Audio Video Standard) (AVS1-P2, JiZhun profile)",
        "cdgraphics": "CD Graphics video",
        "cdxl": "Commodore CDXL video",
        "cfhd": "Cineform HD",
        "cinepak": "Cinepak",
        "clearvideo": "Iterated Systems ClearVideo",
        "cljr": "Cirrus Logic AccuPak",
        "cllc": "Canopus Lossless Codec",
        "cmv": "Electronic Arts CMV video",
        "cpia": "CPiA video format",
        "cscd": "CamStudio",
        "cyuv": "Creative YUV (CYUV)",
        "daala": "Daala",
        "dfa": "Chronomaster DFA",
        "dirac": "Dirac",
        "dnxhd": "VC3/DNxHD",
        "dsicinvideo": "Delphine Software International CIN video",
        "dvvideo": "DV (Digital Video)",
        "dxa": "Feeble Files/ScummVM DXA",
        "dxtory": "Dxtory",
        "dxv": "Resolume DXV",
        "escape124": "Escape 124",
        "escape130": "Escape 130",
        "ffv1": "FFmpeg video codec #1",
        "ffvhuff": "Huffyuv FFmpeg variant",
        "fic": "Mirillis FIC",
        "flashsv": "Flash Screen Video v1",
        "flashsv2": "Flash Screen Video v2",
        "flic": "Autodesk Animator Flic video",
        "flv1": "FLV / Sorenson Spark / Sorenson H.263 (Flash Video)",
        "fmvc": "FM Screen Capture Codec",
        "fraps": "Fraps",
        "frwu": "Forward Uncompressed",
        "g2m": "Go2Meeting",
        "gdv": "Gremlin Digital Video",
        "gif": "GIF (Graphics Interchange Format)",
        "h261": "H.261",
        "h263": "H.263 / H.263-1996, H.263+ / H.263-1998 / H.263 version 2",
        "h263i": "Intel H.263",
        "h263p": "H.263+ / H.263-1998 / H.263 version 2",
        "h264": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
        "hap": "Vidvox Hap",
        "hevc": "H.265 / HEVC (High Efficiency Video Coding)",
        "hnm4video": "HNM 4 video",
        "hq_hqa": "Canopus HQ/HQA",
        "hqx": "Canopus HQX",
        "huffyuv": "HuffYUV",
        "idcin": "id Quake II CIN video (decoders: idcinvideo )",
        "idf": "iCEDraw text",
        "iff_ilbm": "IFF ACBM/ANIM/DEEP/ILBM/PBM/RGB8/RGBN",
        "imm4": "Infinity IMM4",
        "indeo2": "Intel Indeo 2",
        "indeo3": "Intel Indeo 3",
        "indeo4": "Intel Indeo Video Interactive 4",
        "indeo5": "Intel Indeo Video Interactive 5",
        "interplayvideo": "Interplay MVE video",
        "jpegls": "JPEG-LS",
        "jv": "Bitmap Brothers JV video",
        "kgv1": "Kega Game Video",
        "kmvc": "Karl Morton's video codec",
        "lagarith": "Lagarith lossless",
        "ljpeg": "Lossless JPEG",
        "loco": "LOCO",
        "m101": "Matrox Uncompressed SD",
        "mad": "Electronic Arts Madcow Video",
        "magicyuv": "MagicYUV video",
        "mdec": "Sony PlayStation MDEC (Motion DECoder)",
        "mimic": "Mimic",
        "mjpeg": "Motion JPEG",
        "mjpegb": "Apple MJPEG-B",
        "mmvideo": "American Laser Games MM Video",
        "motionpixels": "Motion Pixels video",
        "mpeg1video": "MPEG-1 video",
        "mpeg2video": "MPEG-2 video",
        "mpeg4": "MPEG-4 part 2",
        "msa1": "MS ATC Screen",
        "mscc": "Mandsoft Screen Capture Codec",
        "msmpeg4v1": "MPEG-4 part 2 Microsoft variant version 1",
        "msmpeg4v2": "MPEG-4 part 2 Microsoft variant version 2",
        "msmpeg4v3": "MPEG-4 part 2 Microsoft variant version 3",
        "msrle": "Microsoft RLE",
        "mss1": "MS Screen 1",
        "mss2": "MS Windows Media Video V9 Screen",
        "msvideo1": "Microsoft Video 1",
        "mszh": "LCL (LossLess Codec Library) MSZH",
        "mts2": "MS Expression Encoder Screen",
        "mvc1": "Silicon Graphics Motion Video Compressor 1",
        "mvc2": "Silicon Graphics Motion Video Compressor 2",
        "mwsc": "MatchWare Screen Capture Codec",
        "mxpeg": "Mobotix MxPEG video",
        "nuv": "NuppelVideo/RTJPEG",
        "paf_video": "Amazing Studio Packed Animation File Video",
        "pictor": "Pictor/PC Paint",
        "pixlet": "Apple Pixlet",
        "prores": "Apple ProRes (iCodec Pro)",
        "prosumer": "Brooktree ProSumer Video",
        "psd": "Photoshop PSD file",
        "qdraw": "Apple QuickDraw",
        "qpeg": "Q-team QPEG",
        "qtrle": "QuickTime Animation (RLE) video",
        "r10k": "AJA Kona 10-bit RGB Codec",
        "r210": "Uncompressed RGB 10-bit",
        "rasc": "RemotelyAnywhere Screen Capture",
        "rawvideo": "raw video",
        "rl2": "RL2 video",
        "roq": "id RoQ video",
        "rpza": "QuickTime video (RPZA)",
        "rscc": "innoHeim/Rsupport Screen Capture Codec",
        "rv10": "RealVideo 1.0",
        "rv20": "RealVideo 2.0",
        "rv30": "RealVideo 3.0",
        "rv40": "RealVideo 4.0",
        "sanm": "LucasArts SANM/SMUSH video",
        "scpr": "ScreenPressor",
        "screenpresso": "Screenpresso",
        "sgirle": "SGI RLE 8-bit",
        "sheervideo": "BitJazz SheerVideo",
        "smackvideo": "Smacker video",
        "smc": "QuickTime Graphics (SMC)",
        "smvjpeg": "Sigmatel Motion Video",
        "snow": "Snow",
        "sp5x": "Sunplus JPEG (SP5X)",
        "speedhq": "NewTek SpeedHQ",
        "srgc": "Screen Recorder Gold Codec",
        "svg": "Scalable Vector Graphics",
        "svq1": "Sorenson Vector Quantizer 1 / Sorenson Video 1 / SVQ1",
        "svq3": "Sorenson Vector Quantizer 3 / Sorenson Video 3 / SVQ3",
        "targa_y216": "Pinnacle TARGA CineWave YUV16",
        "tdsc": "TDSC",
        "tgq": "Electronic Arts TGQ video",
        "tgv": "Electronic Arts TGV video",
        "theora": "Theora",
        "thp": "Nintendo Gamecube THP video",
        "tiertexseqvideo": "Tiertex Limited SEQ video",
        "tmv": "8088flex TMV",
        "tqi": "Electronic Arts TQI video",
        "truemotion1": "Duck TrueMotion 1.0",
        "truemotion2": "Duck TrueMotion 2.0",
        "truemotion2rt": "Duck TrueMotion 2.0 Real Time",
        "tscc": "TechSmith Screen Capture Codec",
        "tscc2": "TechSmith Screen Codec 2",
        "ulti": "IBM UltiMotion",
        "utvideo": "Ut Video",
        "v210": "Uncompressed 4:2:2 10-bit",
        "v210x": "Uncompressed 4:2:2 10-bit",
        "v308": "Uncompressed packed 4:4:4",
        "v408": "Uncompressed packed QT 4:4:4:4",
        "v410": "Uncompressed 4:4:4 10-bit",
        "vb": "Beam Software VB",
        "vble": "VBLE Lossless Codec",
        "vc1": "SMPTE VC-1",
        "vcr1": "ATI VCR1",
        "vixl": "Miro VideoXL",
        "vmdvideo": "Sierra VMD video",
        "vmnc": "VMware Screen Codec / VMware Video",
        "vp3": "On2 VP3",
        "vp5": "On2 VP5",
        "vp6": "On2 VP6",
        "vp6a": "On2 VP6 (Flash version, with alpha channel)",
        "vp6f": "On2 VP6 (Flash version)",
        "vp7": "On2 VP7",
        "vp8": "On2 VP8",
        "vp9": "Google VP9",
        "wcmv": "WinCAM Motion Video",
        "webp": "WebP",
        "wmv1": "Windows Media Video 7",
        "wmv2": "Windows Media Video 8",
        "wmv3": "Windows Media Video 9",
        "wnv1": "Winnov WNV1",
        "wrapped_avframe": "AVFrame to AVPacket passthrough",
        "ws_vqa": "Westwood Studios VQA (Vector Quantized Animation) video",
        "xan_wc3": "Wing Commander III / Xan",
        "xan_wc4": "Wing Commander IV / Xxan",
        "xbin": "eXtended BINary text",
        "y41p": "Uncompressed YUV 4:1:1 12-bit",
        "ylc": "YUY2 Lossless Codec",
        "yop": "Psygnosis YOP Video",
        "yuv4": "Uncompressed packed 4:2:0",
        "zerocodec": "ZeroCodec Lossless Video",
        "zlib": "LCL (LossLess Codec Library) ZLIB",
        "zmbv": "Zip Motion Blocks Video",
    },
    CODECS_AUDIO: {
        '4gv': "4GV (Fourth Generation Vocoder)",
        '8svx_exp': "8SVX exponential",
        '8svx_fib': "8SVX fibonacci",
        'aac': "AAC (Advanced Audio Coding)",
        'aac_latm': "AAC LATM (Advanced Audio Coding LATM syntax)",
        'ac3': "ATSC A/52A (AC-3)",
        'adpcm_4xm': "ADPCM 4X Movie",
        'adpcm_adx': "SEGA CRI ADX ADPCM",
        'adpcm_afc': "ADPCM Nintendo Gamecube AFC",
        'adpcm_aica': "ADPCM Yamaha AICA",
        'adpcm_ct': "ADPCM Creative Technology",
        'adpcm_dtk': "ADPCM Nintendo Gamecube DTK",
        'adpcm_ea': "ADPCM Electronic Arts",
        'adpcm_ea_maxis_xa': "ADPCM Electronic Arts Maxis CDROM XA",
        'adpcm_ea_r1': "ADPCM Electronic Arts R1",
        'adpcm_ea_r2': "ADPCM Electronic Arts R2",
        'adpcm_ea_r3': "ADPCM Electronic Arts R3",
        'adpcm_ea_xas': "ADPCM Electronic Arts XAS",
        'adpcm_g722': "G.722 ADPCM",
        'adpcm_g726': "G.726 ADPCM",
        'adpcm_g726le': "G.726 ADPCM little-endian",
        'adpcm_ima_amv': "ADPCM IMA AMV",
        'adpcm_ima_apc': "ADPCM IMA CRYO APC",
        'adpcm_ima_dat4': "ADPCM IMA Eurocom DAT4",
        'adpcm_ima_dk3': "ADPCM IMA Duck DK3",
        'adpcm_ima_dk4': "ADPCM IMA Duck DK4",
        'adpcm_ima_ea_eacs': "ADPCM IMA Electronic Arts EACS",
        'adpcm_ima_ea_sead': "ADPCM IMA Electronic Arts SEAD",
        'adpcm_ima_iss': "ADPCM IMA Funcom ISS",
        'adpcm_ima_oki': "ADPCM IMA Dialogic OKI",
        'adpcm_ima_qt': "ADPCM IMA QuickTime",
        'adpcm_ima_rad': "ADPCM IMA Radical",
        'adpcm_ima_smjpeg': "ADPCM IMA Loki SDL MJPEG",
        'adpcm_ima_wav': "ADPCM IMA WAV",
        'adpcm_ima_ws': "ADPCM IMA Westwood",
        'adpcm_ms': "ADPCM Microsoft",
        'adpcm_mtaf': "ADPCM MTAF",
        'adpcm_psx': "ADPCM Playstation",
        'adpcm_sbpro_2': "ADPCM Sound Blaster Pro 2-bit",
        'adpcm_sbpro_3': "ADPCM Sound Blaster Pro 2.6-bit",
        'adpcm_sbpro_4': "ADPCM Sound Blaster Pro 4-bit",
        'adpcm_swf': "ADPCM Shockwave Flash",
        'adpcm_thp': "ADPCM Nintendo THP",
        'adpcm_thp_le': "ADPCM Nintendo THP (Little-Endian)",
        'adpcm_vima': "LucasArts VIMA audio",
        'adpcm_xa': "ADPCM CDROM XA",
        'adpcm_yamaha': "ADPCM Yamaha",
        'alac': "ALAC (Apple Lossless Audio Codec)",
        'amr_nb': "AMR-NB (Adaptive Multi-Rate NarrowBand)",
        'amr_wb': "AMR-WB (Adaptive Multi-Rate WideBand)",
        'ape': "Monkey's Audio",
        'aptx': "aptX (Audio Processing Technology for Bluetooth)",
        'aptx_hd': "aptX HD (Audio Processing Technology for Bluetooth)",
        'atrac1': "ATRAC1 (Adaptive TRansform Acoustic Coding)",
        'atrac3': "ATRAC3 (Adaptive TRansform Acoustic Coding 3)",
        'atrac3al': "ATRAC3 AL (Adaptive TRansform Acoustic Coding 3 Advanced Lossless)",
        'atrac3p': "ATRAC3+ (Adaptive TRansform Acoustic Coding 3+)",
        'atrac3pal': "ATRAC3+ AL (Adaptive TRansform Acoustic Coding 3+ Advanced Lossless)",
        'atrac9': "ATRAC9 (Adaptive TRansform Acoustic Coding 9)",
        'avc': "On2 Audio for Video Codec",
        'binkaudio_dct': "Bink Audio (DCT)",
        'binkaudio_rdft': "Bink Audio (RDFT)",
        'bmv_audio': "Discworld II BMV audio",
        'celt': "Constrained Energy Lapped Transform (CELT)",
        'codec2': "codec2 (very low bitrate speech codec)",
        'comfortnoise': "RFC 3389 Comfort Noise",
        'cook': "Cook / Cooker / Gecko (RealAudio G2)",
        'dolby_e': "Dolby E",
        'dsd_lsbf': "DSD (Direct Stream Digital), least significant bit first",
        'dsd_lsbf_planar': "DSD (Direct Stream Digital), least significant bit first, planar",
        'dsd_msbf': "DSD (Direct Stream Digital), most significant bit first",
        'dsd_msbf_planar': "DSD (Direct Stream Digital), most significant bit first, planar",
        'dsicinaudio': "Delphine Software International CIN audio",
        'dss_sp': "Digital Speech Standard - Standard Play mode (DSS SP)",
        'dst': "DST (Direct Stream Transfer)",
        'dts': "DCA (DTS Coherent Acoustics)",
        'dvaudio': "DV audio",
        'eac3': "ATSC A/52B (AC-3, E-AC-3)",
        'evrc': "EVRC (Enhanced Variable Rate Codec)",
        'flac': "FLAC (Free Lossless Audio Codec)",
        'g723_1': "G.723.1",
        'g729': "G.729",
        'gremlin_dpcm': "DPCM Gremlin",
        'gsm': "GSM",
        'gsm_ms': "GSM Microsoft variant",
        'iac': "IAC (Indeo Audio Coder)",
        'ilbc': "iLBC (Internet Low Bitrate Codec)",
        'imc': "IMC (Intel Music Coder)",
        'interplay_dpcm': "DPCM Interplay",
        'interplayacm': "Interplay ACM",
        'mace3:MACE (Macintosh Audio Compression/Expansion) 3': "1",
        'mace6:MACE (Macintosh Audio Compression/Expansion) 6': "1",
        'metasound': "Voxware MetaSound",
        'mlp': "MLP (Meridian Lossless Packing)",
        'mp1': "MP1 (MPEG audio layer 1)",
        'mp2': "MP2 (MPEG audio layer 2)",
        'mp3': "MP3 (MPEG audio layer 3)",
        'mp3adu': "ADU (Application Data Unit) MP3 (MPEG audio layer 3)",
        'mp3on4': "MP3onMP4",
        'mp4als': "MPEG-4 Audio Lossless Coding (ALS)",
        'musepack7': "Musepack SV7",
        'musepack8': "Musepack SV8",
        'nellymoser': "Nellymoser Asao",
        'opus': "Opus (Opus Interactive Audio Codec)",
        'paf_audio': "Amazing Studio Packed Animation File Audio",
        'pcm_alaw': "PCM A-law / G.711 A-law",
        'pcm_bluray': "PCM signed 16|20|24-bit big-endian for Blu-ray media",
        'pcm_dvd': "PCM signed 20|24-bit big-endian",
        'pcm_f16le': "PCM 16.8 floating point little-endian",
        'pcm_f24le': "PCM 24.0 floating point little-endian",
        'pcm_f32be': "PCM 32-bit floating point big-endian",
        'pcm_f32le': "PCM 32-bit floating point little-endian",
        'pcm_f64be': "PCM 64-bit floating point big-endian",
        'pcm_f64le': "PCM 64-bit floating point little-endian",
        'pcm_lxf': "PCM signed 20-bit little-endian planar",
        'pcm_mulaw': "PCM mu-law / G.711 mu-law",
        'pcm_s16be': "PCM signed 16-bit big-endian",
        'pcm_s16be_planar': "PCM signed 16-bit big-endian planar",
        'pcm_s16le': "PCM signed 16-bit little-endian",
        'pcm_s16le_planar': "PCM signed 16-bit little-endian planar",
        'pcm_s24be': "PCM signed 24-bit big-endian",
        'pcm_s24daud': "PCM D-Cinema audio signed 24-bit",
        'pcm_s24le': "PCM signed 24-bit little-endian",
        'pcm_s24le_planar': "PCM signed 24-bit little-endian planar",
        'pcm_s32be': "PCM signed 32-bit big-endian",
        'pcm_s32le': "PCM signed 32-bit little-endian",
        'pcm_s32le_planar': "PCM signed 32-bit little-endian planar",
        'pcm_s64be': "PCM signed 64-bit big-endian",
        'pcm_s64le': "PCM signed 64-bit little-endian",
        'pcm_s8': "PCM signed 8-bit",
        'pcm_s8_planar': "PCM signed 8-bit planar",
        'pcm_u16be': "PCM unsigned 16-bit big-endian",
        'pcm_u16le': "PCM unsigned 16-bit little-endian",
        'pcm_u24be': "PCM unsigned 24-bit big-endian",
        'pcm_u24le': "PCM unsigned 24-bit little-endian",
        'pcm_u32be': "PCM unsigned 32-bit big-endian",
        'pcm_u32le': "PCM unsigned 32-bit little-endian",
        'pcm_u8': "PCM unsigned 8-bit",
        'pcm_vidc': "PCM Archimedes VIDC",
        'pcm_zork': "PCM Zork",
        'qcelp': "QCELP / PureVoice",
        'qdm2': "QDesign Music Codec 2",
        'qdmc': "QDesign Music",
        'ra_144': "RealAudio 1.0 (14.4K)",
        'ra_288': "RealAudio 2.0 (28.8K)",
        'ralf': "RealAudio Lossless",
        'roq_dpcm': "DPCM id RoQ",
        's302m': "SMPTE 302M",
        'sbc': "SBC (low-complexity subband codec)",
        'sdx2_dpcm': "DPCM Squareroot-Delta-Exact",
        'shorten': "Shorten",
        'sipr': "RealAudio SIPR / ACELP.NET",
        'smackaudio': "Smacker audio",
        'smv': "SMV (Selectable Mode Vocoder)",
        'sol_dpcm': "DPCM Sol",
        'sonic': "Sonic",
        'sonicls': "Sonic lossless",
        'speex': "Speex",
        'tak': "TAK (Tom's lossless Audio Kompressor)",
        'truehd': "TrueHD",
        'truespeech': "DSP Group TrueSpeech",
        'tta': "TTA (True Audio)",
        'twinvq': "VQF TwinVQ",
        'vmdaudio': "Sierra VMD audio",
        'vorbis': "Vorbis",
        'wavesynth': "Wave synthesis pseudo-codec",
        'wavpack': "WavPack",
        'westwood_snd1': "Westwood Audio (SND1)",
        'wmalossless': "Windows Media Audio Lossless",
        'wmapro': "Windows Media Audio 9 Professional",
        'wmav1': "Windows Media Audio 1",
        'wmav2': "Windows Media Audio 2",
        'wmavoice': "Windows Media Audio Voice",
        'xan_dpcm': "DPCM Xan",
        'xma1': "Xbox Media Audio 1",
        'xma2': "Xbox Media Audio 2",
    },
    CODECS_SUBTITLE: {
        'ass': "ASS (Advanced SSA) subtitle",
        'dvb_subtitle': "DVB subtitles",
        'dvb_teletext': "DVB teletext",
        'dvd_subtitle': "DVD subtitles",
        'eia_608': "EIA-608 closed captions",
        'hdmv_pgs_subtitle': "HDMV Presentation Graphic Stream subtitles",
        'hdmv_text_subtitle': "HDMV Text subtitle",
        'jacosub': "JACOsub subtitle",
        'microdvd': "MicroDVD subtitle",
        'mov_text': "MOV text",
        'mpl2': "MPL2 subtitle",
        'pjs': "PJS (Phoenix Japanimation Society) subtitle",
        'realtext': "RealText subtitle",
        'sami': "SAMI subtitle",
        'srt': "SubRip subtitle with embedded timing",
        'ssa': "SSA (SubStation Alpha) subtitle",
        'stl': "Spruce subtitle format",
        'subrip': "SubRip subtitle",
        'subviewer': "SubViewer subtitle",
        'subviewer1': "SubViewer v1 subtitle",
        'text': "raw UTF-8 text",
        'ttml': "Timed Text Markup Language",
        'vplayer': "VPlayer subtitle",
        'webvtt': "WebVTT subtitle",
        'xsub': "XSUB",
    },
    ENCODERS: {
        'av1': 'libaom-av1',
        'cmv': 'eacmv',
        'cscd': 'camstudio',
        'dirac': 'vc2',
        'flv1': 'flv',
        'h264': 'libx264',
        'hevc': 'libx265',
        'dcin': 'idcinvideo',
        'iff_ilbm': 'iff',
        'jpeg2000': 'libopenjpeg',
        'mad': 'eamad',
        'mpeg2video': 'mpeg2video',
        'mpeg4': 'mpeg4',
        'msmpeg4v3': 'msmpeg4',
        'roq': 'roqvideo',
        'smackvideo': 'smackvid',
        'tgq': 'eatgq',
        'tgv': 'eatgv',
        'theora': 'libtheora',
        'tqi': 'eatqi',
        'tscc': 'camtasia',
        'ulti': 'ultimotion',
        'vixl': 'xl',
        'vp8': 'libvpx',
        'vp9': 'libvpx-vp9',
        'ws_vqa': 'vqavideo',
        "adpcm_g722": "g722",
        "adpcm_g726": "g726",
        "adpcm_g726le": "g726le",
        "amr_nb": "libopencore_amrnb",
        "dts": "dca",
        "ilbc": "ilbc_at",
        "mp3": "libmp3lame",
        "opus": "libopus",
        "ra_144": "real_144",
        "ra_288": "real_288",
        "smackaudio": "smackaud",
        "speex": "libspeex",
        "vorbis": "libvorbis",
        "westwood_snd1": "ws_snd1",
    },
    H264_PRESETS: {
        'ultrafast': 'ultrafast',
        'superfast': 'superfast',
        'veryfast': 'veryfast',
        'faster': 'faster',
        'fast': 'fast',
        'medium': 'medium (default)',
        'slow': 'slow',
        'slower': 'slower',
        'veryslow': 'veryslow',
    },
    H264_PROFILES: {
        'baseline': 'baseline',
        'main': 'main',
        'high': 'high',
        'high10': 'high10',
        'high422': 'high422',
        'high444': 'high444',
    },
    AUDIO_RATES: {
        '8000': '8 khz',
        '16000': '16 khz',
        '24000': '24 khz',
        '32000': '32 khz',
        '44100': '44 khz',
        '48000': '48 khz',
    },
    AUDIO_BITRATES: {
        '32k': '32 kbp/s',
        '48k': '48 kbp/s',
        '96k': '96 kbp/s',
        '128k': '128 kbp/s',
        '160k': '160 kbp/s',
        '192k': '192 kbp/s',
        '256k': '256 kbp/s',
        '320k': '320 kbp/s',
        '448k': '448 kbp/s',
        '512k': '512 kbp/s',
        '640k': '640 kbp/s',
    },
    AUDIO_VBR: {
        '0': '0 (better)',
        '1': '1',
        '2': '2',
        '3': '3',
        '4': '4',
        '5': '5',
        '6': '6',
        '7': '7',
        '8': '8',
        '9': '9',
        '10': '10 (lower)'
    },
    AUDIO_CHANNELS: {
        '1': 'Mono',
        '2': 'Stereo',
        '3': '2.1',
        '6': '5.1',
        '8': '7.2',
    },
    EXAMPLE: require('./input_example'),
    LANGS: {
        "aar": "Afar",
        "abk": "Abkhazian",
        "ace": "Achinese",
        "ach": "Acoli",
        "ada": "Adangme",
        "ady": "Adygei",
        "afa": "Afro-Asiatic Languages",
        "afh": "Afrihili",
        "afr": "Afrikaans",
        "ain": "Ainu",
        "aka": "Akan",
        "akk": "Akkadian",
        "alb": "Albanian",
        "sqi": "Albanian",
        "ale": "Aleut",
        "alg": "Algonquian Languages",
        "alt": "Southern Altai",
        "amh": "Amharic",
        "ang": "English Old (ca.450-1100)",
        "anp": "Angika",
        "apa": "Apache Languages",
        "ara": "Arabic",
        "arc": "Imperial Aramaic (700-300 BCE)",
        "arg": "Aragonese",
        "arm": "Armenian",
        "hye": "Armenian",
        "arn": "Mapuche",
        "arp": "Arapaho",
        "art": "Artificial Languages",
        "arw": "Arawak",
        "asm": "Assamese",
        "ast": "Asturian",
        "ath": "Athapascan Languages",
        "aus": "Australian Languages",
        "ava": "Avaric",
        "ave": "Avestan",
        "awa": "Awadhi",
        "aym": "Aymara",
        "aze": "Azerbaijani",
        "bad": "Banda Languages",
        "bai": "Bamileke Languages",
        "bak": "Bashkir",
        "bal": "Baluchi",
        "bam": "Bambara",
        "ban": "Balinese",
        "baq": "Basque",
        "eus": "Basque",
        "bas": "Basa",
        "bat": "Baltic Languages",
        "bej": "Bedawiyet",
        "bel": "Belarusian",
        "bem": "Bemba",
        "ben": "Bengali",
        "ber": "Berber Languages",
        "bho": "Bhojpuri",
        "bih": "Bihari Languages",
        "bik": "Bikol",
        "bin": "Bini",
        "bis": "Bislama",
        "bla": "Siksika",
        "bnt": "Bantu (Other)",
        "bos": "Bosnian",
        "bra": "Braj",
        "bre": "Breton",
        "btk": "Batak Languages",
        "bua": "Buriat",
        "bug": "Buginese",
        "bul": "Bulgarian",
        "bur": "Burmese",
        "mya": "Burmese",
        "byn": "Bilin",
        "cad": "Caddo",
        "cai": "Central American Indian Languages",
        "car": "Galibi Carib",
        "cat": "Catalan",
        "cau": "Caucasian Languages",
        "ceb": "Cebuano",
        "cel": "Celtic Languages",
        "cha": "Chamorro",
        "chb": "Chibcha",
        "che": "Chechen",
        "chg": "Chagatai",
        "chi": "Chinese",
        "zho": "Chinese",
        "chk": "Chuukese",
        "chm": "Mari",
        "chn": "Chinook Jargon",
        "cho": "Choctaw",
        "chp": "Chipewyan",
        "chr": "Cherokee",
        "chu": "Church Slavic",
        "chv": "Chuvash",
        "chy": "Cheyenne",
        "cmc": "Chamic Languages",
        "cop": "Coptic",
        "cor": "Cornish",
        "cos": "Corsican",
        "cpe": "Creoles And Pidgins",
        "cpf": "Creoles And Pidgins",
        "cpp": "Creoles And Pidgins",
        "cre": "Cree",
        "crh": "Crimean Tatar",
        "crp": "Creoles And Pidgins",
        "csb": "Kashubian",
        "cus": "Cushitic Languages",
        "cze": "Czech",
        "ces": "Czech",
        "dak": "Dakota",
        "dan": "Danish",
        "dar": "Dargwa",
        "day": "Land Dayak Languages",
        "del": "Delaware",
        "den": "Slave (Athapascan)",
        "dgr": "Dogrib",
        "din": "Dinka",
        "div": "Dhivehi",
        "doi": "Dogri",
        "dra": "Dravidian Languages",
        "dsb": "Lower Sorbian",
        "dua": "Duala",
        "dum": "Dutch Middle (ca.1050-1350)",
        "dut": "Dutch",
        "nld": "Dutch",
        "dyu": "Dyula",
        "dzo": "Dzongkha",
        "efi": "Efik",
        "egy": "Egyptian (Ancient)",
        "eka": "Ekajuk",
        "elx": "Elamite",
        "eng": "English",
        "enm": "English Middle (1100-1500)",
        "epo": "Esperanto",
        "est": "Estonian",
        "ewe": "Ewe",
        "ewo": "Ewondo",
        "fan": "Fang",
        "fao": "Faroese",
        "fat": "Fanti",
        "fij": "Fijian",
        "fil": "Filipino",
        "fin": "Finnish",
        "fiu": "Finno-Ugrian Languages",
        "fon": "Fon",
        "fre": "French",
        "fra": "French",
        "frm": "French Middle (ca.1400-1600)",
        "fro": "French Old (842-ca.1400)",
        "frr": "Northern Frisian",
        "frs": "Eastern Frisian",
        "fry": "Western Frisian",
        "ful": "Fulah",
        "fur": "Friulian",
        "gaa": "Ga",
        "gay": "Gayo",
        "gba": "Gbaya",
        "gem": "Germanic Languages",
        "geo": "Georgian",
        "kat": "Georgian",
        "ger": "German",
        "deu": "German",
        "gez": "Geez",
        "gil": "Gilbertese",
        "gla": "Gaelic",
        "gle": "Irish",
        "glg": "Galician",
        "glv": "Manx",
        "gmh": "German Middle High (ca.1050-1500)",
        "goh": "German Old High (ca.750-1050)",
        "gon": "Gondi",
        "gor": "Gorontalo",
        "got": "Gothic",
        "grb": "Grebo",
        "grc": "Greek Ancient (to 1453)",
        "gre": "Greek Modern (1453-)",
        "ell": "Greek Modern (1453-)",
        "grn": "Guarani",
        "gsw": "Alemannic",
        "guj": "Gujarati",
        "gwi": "Gwich'in",
        "hai": "Haida",
        "hat": "Haitian",
        "hau": "Hausa",
        "haw": "Hawaiian",
        "heb": "Hebrew",
        "her": "Herero",
        "hil": "Hiligaynon",
        "him": "Himachali Languages",
        "hin": "Hindi",
        "hit": "Hittite",
        "hmn": "Hmong",
        "hmo": "Hiri Motu",
        "hrv": "Croatian",
        "hsb": "Upper Sorbian",
        "hun": "Hungarian",
        "hup": "Hupa",
        "iba": "Iban",
        "ibo": "Igbo",
        "ice": "Icelandic",
        "isl": "Icelandic",
        "ido": "Ido",
        "iii": "Nuosu",
        "ijo": "Ijo Languages",
        "iku": "Inuktitut",
        "ile": "Interlingue",
        "ilo": "Iloko",
        "ina": "Interlingua (International Auxiliary Language Association)",
        "inc": "Indic Languages",
        "ind": "Indonesian",
        "ine": "Indo-European Languages",
        "inh": "Ingush",
        "ipk": "Inupiaq",
        "ira": "Iranian Languages",
        "iro": "Iroquoian Languages",
        "ita": "Italian",
        "jav": "Javanese",
        "jbo": "Lojban",
        "jpn": "Japanese",
        "jpr": "Judeo-Persian",
        "jrb": "Judeo-Arabic",
        "kaa": "Kara-Kalpak",
        "kab": "Kabyle",
        "kac": "Jingpho",
        "kal": "Greenlandic",
        "kam": "Kamba",
        "kan": "Kannada",
        "kar": "Karen Languages",
        "kas": "Kashmiri",
        "kau": "Kanuri",
        "kaw": "Kawi",
        "kaz": "Kazakh",
        "kbd": "Kabardian",
        "kha": "Khasi",
        "khi": "Khoisan Languages",
        "khm": "Central Khmer",
        "kho": "Khotanese",
        "kik": "Gikuyu",
        "kin": "Kinyarwanda",
        "kir": "Kirghiz",
        "kmb": "Kimbundu",
        "kok": "Konkani",
        "kom": "Komi",
        "kon": "Kongo",
        "kor": "Korean",
        "kos": "Kosraean",
        "kpe": "Kpelle",
        "krc": "Karachay-Balkar",
        "krl": "Karelian",
        "kro": "Kru Languages",
        "kru": "Kurukh",
        "kua": "Kuanyama",
        "kum": "Kumyk",
        "kur": "Kurdish",
        "kut": "Kutenai",
        "lad": "Ladino",
        "lah": "Lahnda",
        "lam": "Lamba",
        "lao": "Lao",
        "lat": "Latin",
        "lav": "Latvian",
        "lez": "Lezghian",
        "lim": "Limburgan",
        "lin": "Lingala",
        "lit": "Lithuanian",
        "lol": "Mongo",
        "loz": "Lozi",
        "ltz": "Letzeburgesch",
        "lua": "Luba-Lulua",
        "lub": "Luba-Katanga",
        "lug": "Ganda",
        "lui": "Luiseno",
        "lun": "Lunda",
        "luo": "Luo (Kenya And Tanzania)",
        "lus": "Lushai",
        "mac": "Macedonian",
        "mkd": "Macedonian",
        "mad": "Madurese",
        "mag": "Magahi",
        "mah": "Marshallese",
        "mai": "Maithili",
        "mak": "Makasar",
        "mal": "Malayalam",
        "man": "Mandingo",
        "mao": "Maori",
        "mri": "Maori",
        "map": "Austronesian Languages",
        "mar": "Marathi",
        "mas": "Masai",
        "may": "Malay",
        "msa": "Malay",
        "mdf": "Moksha",
        "mdr": "Mandar",
        "men": "Mende",
        "mga": "Irish Middle (900-1200)",
        "mic": "Mi'kmaq",
        "min": "Minangkabau",
        "mis": "Uncoded Languages",
        "mkh": "Mon-Khmer Languages",
        "mlg": "Malagasy",
        "mlt": "Maltese",
        "mnc": "Manchu",
        "mni": "Manipuri",
        "mno": "Manobo Languages",
        "moh": "Mohawk",
        "mon": "Mongolian",
        "mos": "Mossi",
        "mul": "Multiple Languages",
        "mun": "Munda Languages",
        "mus": "Creek",
        "mwl": "Mirandese",
        "mwr": "Marwari",
        "myn": "Mayan Languages",
        "myv": "Erzya",
        "nah": "Nahuatl Languages",
        "nai": "North American Indian Languages",
        "nap": "Neapolitan",
        "nau": "Nauru",
        "nav": "Navaho",
        "nbl": "Ndebele",
        "nde": "Ndebele",
        "ndo": "Ndonga",
        "nds": "Low",
        "nep": "Nepali",
        "new": "Nepal Bhasa",
        "nia": "Nias",
        "nic": "Niger-Kordofanian Languages",
        "niu": "Niuean",
        "nno": "Norwegian",
        "nob": "Bokmål",
        "nog": "Nogai",
        "non": "Norse",
        "nor": "Norwegian",
        "nqo": "N'Ko",
        "nso": "Northern Sotho",
        "nub": "Nubian Languages",
        "nwc": "Classical Nepal Bhasa",
        "nya": "Chewa",
        "nym": "Nyamwezi",
        "nyn": "Nyankole",
        "nyo": "Nyoro",
        "nzi": "Nzima",
        "oci": "Occitan (post 1500)",
        "oji": "Ojibwa",
        "ori": "Oriya",
        "orm": "Oromo",
        "osa": "Osage",
        "oss": "Ossetian",
        "ota": "Turkish Ottoman (1500-1928)",
        "oto": "Otomian Languages",
        "paa": "Papuan Languages",
        "pag": "Pangasinan",
        "pal": "Pahlavi",
        "pam": "Kapampangan",
        "pan": "Panjabi",
        "pap": "Papiamento",
        "pau": "Palauan",
        "peo": "Persian Old (ca.600-400 B.C.)",
        "per": "Persian",
        "fas": "Persian",
        "phi": "Philippine Languages",
        "phn": "Phoenician",
        "pli": "Pali",
        "pol": "Polish",
        "pon": "Pohnpeian",
        "por": "Portuguese",
        "pra": "Prakrit Languages",
        "pro": "Provençal Old (to 1500)",
        "pus": "Pashto",
        "que": "Quechua",
        "raj": "Rajasthani",
        "rap": "Rapanui",
        "rar": "Cook Islands Maori",
        "roa": "Romance Languages",
        "roh": "Romansh",
        "rom": "Romany",
        "rum": "Moldavian",
        "ron": "Moldavian",
        "run": "Rundi",
        "rup": "Aromanian",
        "rus": "Russian",
        "sad": "Sandawe",
        "sag": "Sango",
        "sah": "Yakut",
        "sai": "South American Indian (Other)",
        "sal": "Salishan Languages",
        "sam": "Samaritan Aramaic",
        "san": "Sanskrit",
        "sas": "Sasak",
        "sat": "Santali",
        "scn": "Sicilian",
        "sco": "Scots",
        "sel": "Selkup",
        "sem": "Semitic Languages",
        "sga": "Irish Old (to 900)",
        "sgn": "Sign Languages",
        "shn": "Shan",
        "sid": "Sidamo",
        "sin": "Sinhala",
        "sio": "Siouan Languages",
        "sit": "Sino-Tibetan Languages",
        "sla": "Slavic Languages",
        "slo": "Slovak",
        "slk": "Slovak",
        "slv": "Slovenian",
        "sma": "Southern Sami",
        "sme": "Northern Sami",
        "smi": "Sami Languages",
        "smj": "Lule Sami",
        "smn": "Inari Sami",
        "smo": "Samoan",
        "sms": "Skolt Sami",
        "sna": "Shona",
        "snd": "Sindhi",
        "snk": "Soninke",
        "sog": "Sogdian",
        "som": "Somali",
        "son": "Songhai Languages",
        "sot": "Sotho",
        "spa": "Castilian",
        "srd": "Sardinian",
        "srn": "Sranan Tongo",
        "srp": "Serbian",
        "srr": "Serer",
        "ssa": "Nilo-Saharan Languages",
        "ssw": "Swati",
        "suk": "Sukuma",
        "sun": "Sundanese",
        "sus": "Susu",
        "sux": "Sumerian",
        "swa": "Swahili",
        "swe": "Swedish",
        "syc": "Classical Syriac",
        "syr": "Syriac",
        "tah": "Tahitian",
        "tai": "Tai Languages",
        "tam": "Tamil",
        "tat": "Tatar",
        "tel": "Telugu",
        "tem": "Timne",
        "ter": "Tereno",
        "tet": "Tetum",
        "tgk": "Tajik",
        "tgl": "Tagalog",
        "tha": "Thai",
        "tib": "Tibetan",
        "bod": "Tibetan",
        "tig": "Tigre",
        "tir": "Tigrinya",
        "tiv": "Tiv",
        "tkl": "Tokelau",
        "tlh": "Klingon",
        "tli": "Tlingit",
        "tmh": "Tamashek",
        "tog": "Tonga (Nyasa)",
        "ton": "Tonga (Tonga Islands)",
        "tpi": "Tok Pisin",
        "tsi": "Tsimshian",
        "tsn": "Tswana",
        "tso": "Tsonga",
        "tuk": "Turkmen",
        "tum": "Tumbuka",
        "tup": "Tupi Languages",
        "tur": "Turkish",
        "tut": "Altaic Languages",
        "tvl": "Tuvalu",
        "twi": "Twi",
        "tyv": "Tuvinian",
        "udm": "Udmurt",
        "uga": "Ugaritic",
        "uig": "Uighur",
        "ukr": "Ukrainian",
        "umb": "Umbundu",
        "und": "Undetermined",
        "urd": "Urdu",
        "uzb": "Uzbek",
        "vai": "Vai",
        "ven": "Venda",
        "vie": "Vietnamese",
        "vol": "Volapük",
        "vot": "Votic",
        "wak": "Wakashan Languages",
        "wal": "Walamo",
        "war": "Waray",
        "was": "Washo",
        "wel": "Welsh",
        "cym": "Welsh",
        "wen": "Sorbian Languages",
        "wln": "Walloon",
        "wol": "Wolof",
        "xal": "Kalmyk",
        "xho": "Xhosa",
        "yao": "Yao",
        "yap": "Yapese",
        "yid": "Yiddish",
        "yor": "Yoruba",
        "ypk": "Yupik Languages",
        "zap": "Zapotec",
        "zbl": "Bliss",
        "zen": "Zenaga",
        "zgh": "Standard Moroccan Tamazight",
        "zha": "Chuang",
        "znd": "Zande Languages",
        "zul": "Zulu",
        "zun": "Zuni",
        "zxx": "No Linguistic Content",
        "zza": "Dimili"
    },
}
