export default {
    CODECS_VIDEO: {
        'h264': 'H.264 (libx264)',
        'h265': 'H.265 (libx265)',
        'hevc': 'HEVC (libx265)',
        'flv1': 'FLV (flv)',
        'mjpeg': 'Motion JPEG (mjpeg)',
        'mpeg2video': 'MPEG-2 video (mpeg2video)',
        'mpeg4': 'MPEG-4 part 2 (libxvid)',
        'mov': 'QuickTime (mov)',
        'theora': 'Theora (libtheora)',
        'vp8': 'VP8 (libvpx)',
        'vp9': 'Google VP9 (libvpx-vp9)',
        'vcd': 'MPEG-1 Systems (vcd)',
        'vob': 'MPEG-2 PS (vob)',
        'webp': 'WebP (webp)',
        'y41p': '4:1:1 (yuv)',
        'yuv4': '4:2:0 (yuv4)',
    },
    CODECS_AUDIO: {
        'aac': 'AAC (aac)',
        'ac3': 'AC3 (ac3)',
        'alac': 'ALAC (alac)',
        'dts': 'DTS Coherent Acoustics (dca)',
        'eac3': 'E-AC3 (eac3)',
        'mp2': 'MPEG audio layer 2 (mp2)',
        'mp3': 'MPEG audio layer 3 (libmp3lame)',
        'opus': 'OPUS (libopus)',
        'truehd': 'TrueHD (truehd)',
        'vorbis': 'Vorbis (libvorbis)',
    },
    CODECS_SUBTITLE: {
        'ass': 'ASS (ass)',
        'dvb_subtitle': 'DVB subtitles (dvbsub)',
        'dvd_subtitle': 'DVD subtitles (dvdsub)',
        'hdmv_pgs_subtitle': 'HDMV PGS(pgssub)',
        'srt': 'SubRip (srt)',
        'ssa': 'SubStation Alpha (ssa)',
    },
    ENCODERS: {
        'h264': 'libx264',
        'h265': 'libx265',
        'hevc': 'libx265',
        'mpeg4': 'libxvid',
        'theora': 'libtheora',
        'vp8': 'libvpx',
        'vp9': 'libvpx-vp9',
        'mp3': 'libmp3lame',
        'opus': 'libopus',
        'vorbis': 'libvorbis',
        'hdmv_pgs_subtitle': 'pgssub',
    },
    EXAMPLE: require('./input_example'),
    LANGS: {
        'ara': 'Arabic',
        'bel': 'Belarusian',
        'bul': 'Bulgarian',
        'chi': 'Chinese',
        'cze': 'Czech',
        'dan': 'Danish',
        'deu': 'German',
        'eng': 'English',
        'fin': 'Finnish',
        'fre': 'French',
        'heb': 'Hebrew',
        'hin': 'Hindi',
        'ind': 'Indonesian',
        'jpn': 'Japanese',
        'kor': 'Korean',
        'lat': 'Latin',
        'pol': 'Polish',
        'rus': 'Russian',
        'spa': 'Spanish',
        'srp': 'Serbian',
        'swe': 'Swedish',
        'tha': 'Thai',
        'vie': 'Vietnamese',
        'und': 'Undetermined'
    },
}
